artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_path: uploads
  data_path: artifacts/data_ingestion/data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  train_path: artifacts/data_transformation/train.csv
  test_path: artifacts/data_transformation/test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_path: artifacts/data_transformation/train.csv
  
model_evaluation:
  root_dir: artifacts/model_evaluation
  test_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json